version: '3.9'
services:
  api:
    build:
      context: .
      dockerfile: ./apps/ml-api/Dockerfile
      target: production
      args:
        API_PORT: 3000
    command: ["./docker_run_api.sh"]
    ports:
      - 3000:3000

  web:
    build:
      context: .
      dockerfile: ./apps/ml-api-web/Dockerfile
      target: production
      args:
        API_URL: "http://localhost:3000"
        WEB_PORT: 4200
    command: ["./docker_run_web.sh"]
    ports:
      - 3001:4200
    depends_on:
      - api
