
name: Build and publish API

on:
  release:
    types:
      - created

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo # (callout-1)
        uses: actions/checkout@v2
      - name: Build image # (callout-2)
        run: docker build . -t safekids-ai/ml-models-api -f apps/ml-api/Dockerfile
      - name: Install doctl # (callout-3)
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Log in to DO Container Registry # (callout-4)
        run: doctl registry login --expiry-seconds 600
      - name: Tag image # (callout-5)
        run:
          docker tag safekids-ai/ml-models-api registry.digitalocean.com/safekids-ai/ml-models-api:latest
      - name: Push image to DO Container Registry # (callout-6)
        run: docker push registry.digitalocean.com/safekids-ai/ml-models-api:latest
